In [ ]:
#PART-1
#1.Import the pandas library
import pandas as pd

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#2.Load the datset into a DataFram
df=pd.read_csv('/content/online_shopping_uncleaned_20000_rows.csv')
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.0,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,NaN,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,NaN,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.0,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4.0,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,NaN,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,NaN,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,NaN,2.0,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,NaN,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1,2.0,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
#3.Display the first 10 rows.
df.head(10)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.0,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,NaN,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,NaN,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.0,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4.0,returned,chennai,15,NaN,NaN,Platinum
5,5,17850.0,M,Chicago,12.0,16701.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,FAILED,2,2.0,NaN,Delhi,NaN,Low,2,Gold
6,6,17850.0,M,Chicago,12.0,16702.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,NaN,5.0,Not Returned,chennai,unknown,high,unknown,NaN
7,7,17850.0,M,Chicago,12.0,16703.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Pending,7,4.0,returned,Mumbai,10,Low,2,NaN
8,8,17850.0,M,Chicago,12.0,16704.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,4.0,returned,Delhi,5,High,0,Platinum
9,9,17850.0,M,Chicago,12.0,16710.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Paid,10days,NaN,Returned,Mumbai,5,unknown,NaN,Gold

In [ ]:
#4.Display the last 10 rows.
df.tail(10)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
19990,19990,14309.0,F,New Jersey,49.0,30594.0,2019-06-17,GGOEGOLC014299,Google Metallic Notebook Set,Office,...,30.0,Pending,1,1.0,NONE,NaN,unknown,NaN,NaN,NaN
19991,19991,14309.0,F,New Jersey,49.0,30595.0,2019-06-17,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,Paid,NaN,5.0,Not Returned,Chennai,15,NaN,2,Silver
19992,19992,15291.0,M,California,32.0,31203.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,paid,3,3.0,NaN,Unknown,5,unknown,unknown,NaN
19993,19993,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEAFKQ020599,Android Sticker Sheet Ultra Removable,Office,...,30.0,Pending,3,NaN,NaN,NaN,5,Low,3,NaN
19994,19994,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,Paid,7,NaN,Not Returned,chennai,5,Low,3,gold
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,NaN,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,NaN,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,NaN,2.0,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,NaN,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1,2.0,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
#5.Find the total number of rows and columns.
df.shape

(20000, 30)

In [ ]:
#PART-2
#6.Display all column names.
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [ ]:
#7.Check data types of each columns
df.dtypes

Unnamed: 0               int64
CustomerID             float64
Gender                  object
Location                object
Tenure_Months          float64
Transaction_ID         float64
Transaction_Date        object
Product_SKU             object
Product_Description     object
Product_Category        object
Quantity               float64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status           object
GST                    float64
Date                    object
Offline_Spend          float64
Online_Spend           float64
Month                    int64
Coupon_Code             object
Discount_pct           float64
Payment_Status          object
Delivery_Days           object
Customer_Rating        float64
Return_Status           object
Customer_City           object
Discount_Percent        object
Order_Priority          object
Support_Calls           object
Membership              object
dtype: object

In [ ]:
#8.Display summary statistics
df.describe()

,Unnamed: 0,CustomerID,Tenure_Months,Transaction_ID,Quantity,Avg_Price,Delivery_Charges,GST,Offline_Spend,Online_Spend,Month,Discount_pct,Customer_Rating
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,19917.000000,15012.000000
mean,9999.500000,15384.448800,26.419000,31757.398950,4.403900,56.511256,11.07499,0.134707,2998.910000,1960.758028,6.345150,22.944219,3.175793
std,5773.647028,1790.469818,13.522188,10442.150226,21.192688,63.316612,20.61016,0.044485,1116.007655,849.627815,3.993798,7.820770,1.338989
min,0.000000,12347.000000,2.000000,16679.000000,1.000000,0.390000,0.00000,0.050000,500.000000,320.250000,1.000000,10.000000,1.000000
25%,4999.750000,13819.000000,15.000000,22285.000000,1.000000,6.180000,6.00000,0.100000,2000.000000,1296.810000,3.000000,20.000000,2.000000
50%,9999.500000,15311.000000,27.000000,34498.500000,1.000000,19.190000,6.50000,0.100000,3000.000000,1918.530000,8.000000,20.000000,4.000000
75%,14999.250000,17114.000000,38.000000,36871.000000,2.000000,119.000000,6.50000,0.180000,4000.000000,2546.580000,8.000000,30.000000,4.000000
max,19999.000000,18260.000000,50.000000,48497.000000,825.000000,355.740000,521.36000,0.180000,5000.000000,4055.300000,12.000000,30.000000,5.000000

In [ ]:
#9.Count the unique values in each columns
df.nunique()

Unnamed: 0             20000
CustomerID               889
Gender                     2
Location                   5
Tenure_Months             49
Transaction_ID         10153
Transaction_Date         154
Product_SKU             1012
Product_Description      385
Product_Category          20
Quantity                 111
Avg_Price                457
Delivery_Charges         185
Coupon_Status              3
GST                        4
Date                     154
Offline_Spend             11
Online_Spend             154
Month                      5
Coupon_Code                5
Discount_pct               3
Payment_Status             5
Delivery_Days              7
Customer_Rating            5
Return_Status              4
Customer_City              5
Discount_Percent           6
Order_Priority             5
Support_Calls              6
Membership                 4
dtype: int64

In [ ]:
#10.Identify columns with missing values
df.isnull()

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,True,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,True
19996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,False,False
19997,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,True
19998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,True,False,False,False
19999,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False

In [ ]:
#PART-3
#11.Count missing values in each columns
df.isnull().sum()

Unnamed: 0                0
CustomerID                0
Gender                    0
Location                  0
Tenure_Months             0
Transaction_ID            0
Transaction_Date          0
Product_SKU               0
Product_Description       0
Product_Category          0
Quantity                  0
Avg_Price                 0
Delivery_Charges          0
Coupon_Status             0
GST                       0
Date                      0
Offline_Spend             0
Online_Spend              0
Month                     0
Coupon_Code            3356
Discount_pct             83
Payment_Status         3252
Delivery_Days          2395
Customer_Rating        4988
Return_Status          4076
Customer_City          3421
Discount_Percent       2849
Order_Priority         3356
Support_Calls          2856
Membership             6717
dtype: int64

In [ ]:
#12.Replace missinng values in Customer_Rating with mean
df['Customer_Rating'].fillna(df['Customer_Rating'].mean(),inplace=True)
df['Customer_Rating']=df['Customer_Rating'].astype(int)

/tmp/ipykernel_10536/1913451515.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Rating'].fillna(df['Customer_Rating'].mean(),inplace=True)

In [ ]:
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,3,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,3,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,NaN,2,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,3,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1,2,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
#13.Replace missing values in Payment_Status with "Unknown".
df['Payment_Status'].fillna("Unknown",inplace=True)
df

/tmp/ipykernel_10536/3796161730.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment_Status'].fillna("Unknown",inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,10days,3,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,3,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,NaN,2,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,3,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1,2,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
#14 Fill missing values in Delivery_Days using median.
# First, convert 'Delivery_Days' to numeric, coercing errors to NaN
df['Delivery_Days'] = pd.to_numeric(df['Delivery_Days'], errors='coerce')
# Then, fill missing values with the median of the now numeric column
df['Delivery_Days'].fillna(df['Delivery_Days'].median(), inplace=True)
df

/tmp/ipykernel_10536/3482562412.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery_Days'].fillna(df['Delivery_Days'].median(), inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
#15.Replace missing Coupon_Code with "No Coupon".
df['Coupon_Code'].fillna('No Coupon',inplace=True)
df['Coupon_Code']

/tmp/ipykernel_10536/551563363.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Coupon_Code'].fillna('No Coupon',inplace=True)

0          unknown
1             NONE
2          NEWUSER
3          sale20
4        No Coupon
           ...
19995      unknown
19996    No Coupon
19997      unknown
19998         NONE
19999      sale20
Name: Coupon_Code, Length: 20000, dtype: object

In [ ]:
df['Discount_pct'].fillna(df['Discount_pct'].mean(),inplace=True)
df

/tmp/ipykernel_10536/1132603340.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount_pct'].fillna(df['Discount_pct'].mean(),inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
df['Return_Status'].fillna('Unknown',inplace=True)
df

/tmp/ipykernel_10536/231021162.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Return_Status'].fillna('Unknown',inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,Unknown,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,Unknown,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
df['Customer_City'].fillna('Kochi',inplace=True)
df

/tmp/ipykernel_10536/2979581333.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_City'].fillna('Kochi',inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,Unknown,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,Kochi,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
df['Discount_Percent'].fillna(df['Discount_Percent'].mode()[0],inplace=True)
df

/tmp/ipykernel_10536/33812860.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount_Percent'].fillna(df['Discount_Percent'].mode()[0],inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,Unknown,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
df['Order_Priority'].fillna(method='bfill',inplace=True)
df

/tmp/ipykernel_10536/1902747386.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Priority'].fillna(method='bfill',inplace=True)
/tmp/ipykernel_10536/1902747386.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_Priority'].fillna(method='bfill',inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,Low,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
df['Support_Calls'].fillna(method='bfill',inplace=True)
df

/tmp/ipykernel_10536/4283186197.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Support_Calls'].fillna(method='bfill',inplace=True)
/tmp/ipykernel_10536/4283186197.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Support_Calls'].fillna(method='bfill',inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
df['Membership'].fillna(method='bfill',inplace=True)
df

/tmp/ipykernel_10536/734935071.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Membership'].fillna(method='bfill',inplace=True)
/tmp/ipykernel_10536/734935071.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Membership'].fillna(method='bfill',inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
#16 Verify that missing values are handled
df.isnull().sum()

Unnamed: 0             0
CustomerID             0
Gender                 0
Location               0
Tenure_Months          0
Transaction_ID         0
Transaction_Date       0
Product_SKU            0
Product_Description    0
Product_Category       0
Quantity               0
Avg_Price              0
Delivery_Charges       0
Coupon_Status          0
GST                    0
Date                   0
Offline_Spend          0
Online_Spend           0
Month                  0
Coupon_Code            0
Discount_pct           0
Payment_Status         0
Delivery_Days          0
Customer_Rating        0
Return_Status          0
Customer_City          0
Discount_Percent       0
Order_Priority         0
Support_Calls          0
Membership             0
dtype: int64

In [ ]:
#PART - 4
#17.Remove leading and trailing spaces in all string columns.
df=df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3,returned,chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4,returned,chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
#18.Convert Payment_Status to lowercase.
df['Payment_Status']=df['Payment_Status'].str.lower()
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1.0,3,returned,chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3.0,4,returned,chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3.0,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
#19.Standardize values in Customer_City.
df['Customer_City']=df['Customer_City'].str.title()
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1.0,3,returned,Chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3.0,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3.0,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
#20.Clean Coupon_Code (remove extra spaces, make uppercase).
df['Coupon_Code']=df['Coupon_Code'].str.strip().str.upper()
df['Coupon_Code']

0          UNKNOWN
1             NONE
2          NEWUSER
3           SALE20
4        NO COUPON
           ...
19995      UNKNOWN
19996    NO COUPON
19997      UNKNOWN
19998         NONE
19999       SALE20
Name: Coupon_Code, Length: 20000, dtype: object

In [ ]:
#21.Replace "unknown" values with NaN.
import numpy as np
df.replace({'unknown':np.nan})
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1.0,3,returned,Chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3.0,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3.0,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
#22.Replace "NONE" and "none" with NaN.
df.replace({'NONE':np.nan,'none':np.nan})
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1.0,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3.0,3,Unknown,Kochi,25%,Medium,4calls,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3,Returned,Mumbai,unknown,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1.0,3,returned,Chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3.0,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3,returned,Kochi,25%,High,4calls,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3.0,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2,Not Returned,Mumbai,25%,unknown,unknown,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7.0,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1.0,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
#PART - 5
#23.Convert Delivery_Days to numeric (remove "days").
df['Delivery_Days']=df['Delivery_Days'].astype(int)
df['Delivery_Days'].fillna(df['Delivery_Days'].median(), inplace=True)
df

/tmp/ipykernel_10536/3595712338.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery_Days'].fillna(df['Delivery_Days'].median(), inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25%,Medium,4calls,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,unknown,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,returned,Chennai,25%,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,Kochi,25%,High,4calls,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3,3,Unknown,Unknown,unknown,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25%,unknown,unknown,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,returned,Kochi,25%,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25%,Low,4calls,gold

In [ ]:
#24.Convert Discount_Percent to numeric (remove %).
df['Discount_Percent']=df['Discount_Percent'].replace('%', '', regex=True)
df['Discount_Percent']=pd.to_numeric(df['Discount_Percent'],errors='coerce')
df['Discount_Percent'] = df['Discount_Percent'].fillna(df['Discount_Percent'].mode()[0])
df['Discount_Percent']=df['Discount_Percent'].astype(int)
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,returned,Unknown,25,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25,Medium,4calls,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,25,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,returned,Chennai,25,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,Kochi,25,High,4calls,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3,3,Unknown,Unknown,25,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,unknown,unknown,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,returned,Kochi,25,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,4calls,gold

In [ ]:
#25.Convert Support_Calls to numeric (remove "calls").
df['Support_Calls']=df['Support_Calls'].replace('Call','',regex=True)
df['Support_Calls']=pd.to_numeric(df['Support_Calls'],errors='coerce')
df['Support_Calls']=df['Support_Calls'].fillna(df['Support_Calls'].mode()[0])
df['Support_Calls']=df['Support_Calls'].astype(int)
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,returned,Unknown,25,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25,Medium,3,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,25,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,returned,Chennai,25,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,Kochi,25,High,3,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3,3,Unknown,Unknown,25,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,unknown,3,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,returned,Kochi,25,unknown,3,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,3,gold

In [ ]:
#26.Convert Customer_Rating to numeric.
df['Customer_Rating']=pd.to_numeric(df['Customer_Rating'])
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,returned,Unknown,25,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25,Medium,3,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,25,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,returned,Chennai,25,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,Kochi,25,High,3,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3,3,Unknown,Unknown,25,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,unknown,3,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,returned,Kochi,25,unknown,3,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,3,gold

In [ ]:
#27.Handle invalid numeric values
df.isnull().sum()

Unnamed: 0             0
CustomerID             0
Gender                 0
Location               0
Tenure_Months          0
Transaction_ID         0
Transaction_Date       0
Product_SKU            0
Product_Description    0
Product_Category       0
Quantity               0
Avg_Price              0
Delivery_Charges       0
Coupon_Status          0
GST                    0
Date                   0
Offline_Spend          0
Online_Spend           0
Month                  0
Coupon_Code            0
Discount_pct           0
Payment_Status         0
Delivery_Days          0
Customer_Rating        0
Return_Status          0
Customer_City          0
Discount_Percent       0
Order_Priority         0
Support_Calls          0
Membership             0
dtype: int64

In [ ]:
#28.Verify updated data types
df.dtypes

Unnamed: 0               int64
CustomerID             float64
Gender                  object
Location                object
Tenure_Months          float64
Transaction_ID         float64
Transaction_Date        object
Product_SKU             object
Product_Description     object
Product_Category        object
Quantity               float64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status           object
GST                    float64
Date                    object
Offline_Spend          float64
Online_Spend           float64
Month                    int64
Coupon_Code             object
Discount_pct           float64
Payment_Status          object
Delivery_Days            int64
Customer_Rating          int64
Return_Status           object
Customer_City           object
Discount_Percent         int64
Order_Priority          object
Support_Calls            int64
Membership              object
dtype: object

In [ ]:
#PART - 6
#29.Check for duplicate rows
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Length: 20000, dtype: bool

In [ ]:
#30.	Count duplicate records
df.duplicated().sum()

np.int64(0)

In [ ]:
#31.Remove duplicate rows.
df.drop_duplicates(inplace=True)
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,returned,Unknown,25,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25,Medium,3,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,25,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,returned,Chennai,25,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,Kochi,25,High,3,gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3,3,Unknown,Unknown,25,unknown,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,unknown,3,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,returned,Kochi,25,unknown,3,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,3,gold

In [ ]:
#32.Display dataset shape after removal
df.shape

(20000, 30)

In [ ]:
#PART - 7
#33.Count total number of orders
len(df)

20000

In [ ]:
#34.Find number of orders by Payment_Status.
df['Payment_Status'].value_counts()

Payment_Status
paid       6627
unknown    6606
failed     3430
pending    3337
Name: count, dtype: int64

In [ ]:
#35.Identify most common payment method/status
df['Payment_Status'].value_counts().idxmax()#idxmax is used to show the most common values

'paid'

In [ ]:
#36.Find total number of returned orders
df[df['Return_Status']=='returned'].shape[0]

3990

In [ ]:
#37.Calculate return percentage.
df[df['Return_Status']=='returned'].shape[0]/len(df)*100

19.950000000000003

In [ ]:
#38.count orders by Order_Priority
df['Order_Priority'].value_counts()

Order_Priority
High      10113
Low        4955
Medium     4932
Name: count, dtype: int64

In [ ]:
#PART - 8
#39.Count number of customers by Customer_City.
df['Customer_City'].value_counts()

Customer_City
Chennai    6580
Kochi      3421
Mumbai     3403
Unknown    3312
Delhi      3284
Name: count, dtype: int64

In [ ]:
#40.Find city with highest orders.
df['Customer_City'].value_counts().idxmax()

'Chennai'

In [ ]:
#41.Find average Customer_Rating
df['Customer_Rating'].mean()

np.float64(3.13195)

In [ ]:
#42.Identify customers with rating less than 3.
df[df['Customer_Rating']<3]

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,returned,Unknown,25,High,3,Gold
5,5,17850.0,M,Chicago,12.0,16701.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,failed,2,2,Unknown,Delhi,25,Low,2,Gold
16,16,17850.0,M,Chicago,12.0,16722.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,paid,2,2,Returned,Delhi,15,unknown,3,Gold
24,24,13047.0,M,California,43.0,16684.0,2019-01-01,GGOENEBQ079199,Nest Protect Smoke + CO White Wired Alarm-USA,Nest-USA,...,10.0,failed,7,2,Returned,Delhi,5,Low,3,Platinum
29,29,14688.0,F,New York,46.0,16732.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,1,returned,Chennai,25,high,3,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19981,19981,14401.0,F,California,20.0,29465.0,2019-06-02,GGOEGOLC014299,Google Metallic Notebook Set,Office,...,30.0,unknown,3,2,Returned,Chennai,25,Medium,2,Silver
19985,19985,15194.0,M,Chicago,33.0,30614.0,2019-06-17,GGOEGGOA017399,Maze Pen,Office,...,30.0,unknown,7,2,Returned,Mumbai,10,high,3,Silver
19990,19990,14309.0,F,New Jersey,49.0,30594.0,2019-06-17,GGOEGOLC014299,Google Metallic Notebook Set,Office,...,30.0,pending,1,1,NONE,Kochi,25,unknown,2,Silver
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,unknown,3,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,3,gold

In [ ]:
df['Membership'] = df['Membership'].replace('gold','Gold')
df['Membership']

0            Gold
1            Gold
2            Gold
3            Gold
4        Platinum
           ...
19995        Gold
19996        Gold
19997        Gold
19998        Gold
19999        Gold
Name: Membership, Length: 20000, dtype: object

In [ ]:
#43.Count customers by Membership type
df['Membership'].value_counts()

Membership
Gold        9912
Platinum    5085
Silver      5003
Name: count, dtype: int64

In [ ]:
#PART - 9
#44.Find average Delivery_Days.
df['Delivery_Days'].mean()

np.float64(3.36745)

In [ ]:
#45.Identify orders with delivery time > 7 days.
df[df['Delivery_Days']>7].shape

(0, 30)

In [ ]:
#46.Count delayed orders
df[df['Delivery_Days']>7].shape[0]

0

In [ ]:
#47.Compare delivery time by Order_Priority
df.groupby('Order_Priority')['Delivery_Days'].mean()

Order_Priority
High      3.369722
Low       3.363673
Medium    3.366586
Name: Delivery_Days, dtype: float64

In [ ]:
#48.Find fastest delivery category.
# Standardize 'Order_Priority' values
df['Order_Priority'] = df['Order_Priority'].replace({'high': 'High'})
df['Order_Priority'] = df['Order_Priority'].replace({'unknown': np.nan})
df['Order_Priority'].fillna(method='bfill', inplace=True)

df.groupby('Order_Priority')['Delivery_Days'].mean().idxmin()
df

/tmp/ipykernel_10536/816077623.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Priority'].fillna(method='bfill', inplace=True)
/tmp/ipykernel_10536/816077623.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_Priority'].fillna(method='bfill', inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,returned,Unknown,25,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25,Medium,3,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,25,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,returned,Chennai,25,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,4,returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,Kochi,25,High,3,Gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3,3,Unknown,Unknown,25,Low,2,Gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,Low,3,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,returned,Kochi,25,Low,3,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,3,Gold

In [ ]:
#PART - 10
#49.Find average Discount_Percent
df['Discount_Percent'].mean()

np.float64(17.8335)

In [ ]:
#50.Identify orders with highest discount
df['Discount_Percent'].max()

25

In [ ]:
#51.Count how many orders used coupons
df[df['Coupon_Status']=='Used'].shape[0]

6761

In [ ]:
#52.Find most used Coupon_Code
df['Coupon_Code'].value_counts().idxmax()

'UNKNOWN'

In [ ]:
#53.Compare price before and after discount (if available).
df.groupby('Coupon_Status')['Discount_Percent'].mean()

Coupon_Status
Clicked     17.795699
Not Used    18.044810
Used        17.793226
Name: Discount_Percent, dtype: float64

In [ ]:
#PART - 11
#54.Find average Support_Calls per order.
df['Support_Calls'].mean()

np.float64(1.9941)

In [ ]:
#55.Identify orders with more than 2 support calls.
df[df['Support_Calls']>2]

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,returned,Unknown,25,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25,Medium,3,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,returned,Chennai,25,Low,3,Gold
6,6,17850.0,M,Chicago,12.0,16702.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,5,Not Returned,Chennai,25,High,3,Platinum
12,12,17850.0,M,Chicago,12.0,16720.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,paid,7,3,Returned,Chennai,25,Medium,3,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,19994,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,paid,7,3,Not Returned,Chennai,5,Low,3,Gold
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,returned,Kochi,25,High,3,Gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,Low,3,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,returned,Kochi,25,Low,3,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,3,Gold

In [ ]:
#56.Find relation between Support_Calls and Return_Status.
df.groupby('Return_Status')['Support_Calls'].mean()

Return_Status
NONE            1.989691
Not Returned    1.991197
Returned        1.990475
Unknown         2.008342
Name: Support_Calls, dtype: float64

In [ ]:
#57.Identify problematic orders (high calls + returns).
df.groupby('Return_Status')['Support_Calls'].sum()

Return_Status
NONE             8106
Not Returned     7917
Returned        15673
Unknown          8186
Name: Support_Calls, dtype: int64

In [ ]:
df['Return_Status'].replace('returned','Returned',inplace=True)
df

/tmp/ipykernel_10536/3973692197.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Return_Status'].replace('returned','Returned',inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,Returned,Unknown,25,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25,Medium,3,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,25,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,Returned,Chennai,25,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,4,Returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,Returned,Kochi,25,High,3,Gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3,3,Unknown,Unknown,25,Low,2,Gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,Low,3,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,Returned,Kochi,25,Low,3,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,3,Gold

In [ ]:
#PART - 12
#58.Save cleaned dataset as clean_online_shopping.csv

In [ ]:
#58.Save cleaned dataset as clean_online_shopping.csv
df.to_csv('clean_online_shopping.csv', index=False)

In [ ]:
from google.colab import files
#59.Export analysis results to CSV.
files.download('clean_online_shopping.csv')

In [ ]:
#60.Display final dataset shape
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,1,1,Returned,Unknown,25,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3,3,Unknown,Kochi,25,Medium,3,Gold
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3,Returned,Mumbai,25,Medium,0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,paid,1,3,Returned,Chennai,25,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,pending,3,4,Returned,Chennai,15,Low,2,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3,Returned,Kochi,25,High,3,Gold
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,paid,3,3,Unknown,Unknown,25,Low,2,Gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3,2,Not Returned,Mumbai,25,Low,3,Gold
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,pending,7,3,Returned,Kochi,25,Low,3,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1,2,Not Returned,Chennai,25,Low,3,Gold